global:
  ingress:
    enabled: false
    addReleaseNameToHost: subdomain
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"

pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: getting-started/pingfederate
    SERVER_PROFILE_PARENT: LICENSE

    SERVER_PROFILE_LICENSE_URL: https://github.com/gmorgan-ping/layered-reference.git
    SERVER_PROFILE_LICENSE_PATH: profiles/pingfederate



pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/gmorgan-ping/profile-run-sh.git
    SERVER_PROFILE_PATH: profiles/pingfederate
    SERVER_PROFILE_PARENT: LICENSE

    SERVER_PROFILE_LICENSE_URL: https://github.com/gmorgan-ping/layered-reference.git
    SERVER_PROFILE_LICENSE_PATH: profiles/pingfederate
